title: PSC 거더교 설계 절차도
description: PSC 거더교 설계 절차도
remote_theme: tomoknetwork/tomoknetwork.github.io

# Theme settings:
site_author: Carlos Pereira Atencio
repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
